apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
        - name: app-b
          image: ghcr.io/huhouhua/opentelemetry-example
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: APP_NAME
              value: "app-b"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-b
  labels:
    app: app-b
spec:
  type: ClusterIP
  ports:
    - port: 8000
      name: web
      targetPort: 8000
  selector:
    app: app-b