rules:
  default: false
  custom:
    - seriesQuery: "http_requests_total"
      resources:
        overrides:
          namespace: { resource: "namespace" }
          pod: { resource: "pod" }
      name:
        matches: "^(.*)_total"
        as: "${1}_qps"
      metricsQuery: (sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>))

prometheus:
  url: http://kube-prometheus-stack-prometheus.monitoring
