apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: week9-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: week9-prometheus-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_qps
        target:
          averageValue: 10
          type: AverageValue
