apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-a
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: app-a
  endpoints:
    - port: web
      interval: 10s
      path: /metrics