apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - result-deployment.yaml
  - result-service.yaml
  - vote-deployment.yaml
  - vote-service.yaml
  - worker-deployment.yaml
