apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-learning
  template:
    metadata:
      labels:
        app: machine-learning
    spec:
      containers:
        - name: machine-learning
          image: ghcr.io/huhouhua/machine-learning:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: machine-learning
spec:
  selector:
    app: machine-learning
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP