deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: loki-1314895130
      ruler: loki-1314895130
      admin: loki-1314895130
    type: s3
    s3:
      endpoint: cos.ap-hongkong.myqcloud.com
      region: ap-hongkong
      secretAccessKey: pQnwrZ3IK8j5II4cv0tXw74mFVWKxNZi
      accessKeyId: AKIDLelkW4NE0jKjz4wa14vYyA8uSlqgJjvu
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: s3
        schema: v13
singleBinary:
  replicas: 1
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
